Restaurant.create(name: 'Frites & Co', address: 'Paris', category: 'belgian', phone_number: '0123456789')
Restaurant.create(name: 'Il Bocaccio', address: 'Nantes', category: 'italian', phone_number: '0123456788')
Restaurant.create(name: 'La raclette', address: 'Meribel', category: 'french', phone_number: '0123456787')
Restaurant.create(name: 'Japan Sakura', address: 'Lyon', category: 'japanese', phone_number: '0123456786')
Restaurant.create(name: 'Le Bonheur', address: 'Saint-Cloud', category: 'chinese', phone_number: '0123456785')
